import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Watch from '../../components/Watch'
import { useEffect, useState } from 'react'
import WatchClass from '../../components/WatchClass';

interface TimeObj {
  hour: string;
  minute: string;
  second: string;
}

export default function Home() {
  const [objTime, setObjTime] = useState({hour: '', minute: '', second: ''});
  const {hour, minute, second }:TimeObj = objTime;

 const getNowTime = async () => {
    let res = await fetch('https://api.api-ninjas.com/v1/worldtime?city=Moscow',  {
      headers: {
        'X-Api-Key': 'FOe02DwgZIv/Tkdd5O4L1g==AzMFqknEL7kWWp00'
      }
    })

    if (!res.ok) {
      throw new Error(`Failed to fetch posts, received status ${res.status}`)
    }

    let data = await res.json();
    setObjTime(data);    

    console.log(data);
  }

  useEffect(() => {
    getNowTime();    
  }, [objTime])  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>       
        <Watch hour={hour} minute={minute} second={second}/>     
        <WatchClass /> 
      </main>
    </>
  )
}
